### ISSUE TITLE
$GOPATH not set when fetching deps

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-engine-golang#13]
Testing an Echo quickstart using the Go engine. Here's the boxfile.yml

```yaml
run.config:
  engine: golang
  engine.config:
    package: nanobox-echo
    fetch: go get
```

In the verbose `nanobox run` output, I get the following when it attempts to `go get`:

```txt
package github.com/labstack/echo: cannot download, $GOPATH not set. For more details see: go help gopath
```
