### ISSUE TITLE
If build fails, don't continue

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-engine-golang#21]
Currently, if the `compiling application step fails, the deploy will continue as if nothing broke

deploy output
```
  Compiling code :
    - Cleaning up any previous releases...
    - Copying code...
    - Compiling application :
      api/api.go:9: imported and not used: "strings"
    
    - After compile hook 1 :
       $ cp -r $CODE_DIR/app $APP_DIR/app
    
    - Moving compiled binary into app directory...
...
```

boxfile.yml
```yaml
run.config:
  engine: golang
  engine.config:
    build: go build --ldflags="-s"
```
