### ISSUE TITLE
Doesn't works with gitea

### ISSUE THREAD

**Issue by lakano** [nanobox-io/nanobox-engine-golang#22]
Hi,

Since 2 days I'm trying different ways to install Gitea with nanobox.io, there is no document guide for Go code from scratch yet. We would like to install Gitea and we've tried the classic golang engine, and with a static system like for your Hugo project. None works. Each time the « gitea » code isn't present. Even if we download the binary in extra_steps, it's not stay in the directory. 

Here is our last try:
```
run.config:
    engine: golang
    engine.config:
        package: go-gitea/gitea
        runtime: go-1.8
        fetch: 'go get'
        build: 'go build'

    # Debian packages
    extra_packages:
        - git

# Repository
data.storage_src:
    image: nanobox/unfs:0.9

web.src:
    start: gitea web
    network_dirs:
        data.storage_src:
            - bin
            - certs
            - repositories
            - custom
            - data
            - log

```

This could be really appreciated if you could help us to understood why this doesn't works.
Best regards,

  PS: BTW, there is a docker image ( https://docs.gitea.io/fr-fr/install-with-docker/ ) but I don't known how to use it inside nanobox...

**Comment by lakano** [comment]
We've also tried:
```
run.config:
    engine: golang
    engine.config:
        package: code.gitea.io/gitea
        runtime: go-1.8
        fetch: 'go get -d -u'
        build: 'make generate all'

    # Debian packages
    extra_packages:
        - git

web.src:
    start: gitea web
```
and static engine:
```
run.config:
    engine: static
    

# Repository
data.storage_src:
    image: nanobox/unfs:0.9

web.src:
    start: gitea web
    network_dirs:
        data.storage_src:
            - bin
            - certs
            - data
            - log
            - custom
            - repositories

```

Each time, the binary gitea is removed by nanobox and can't be called.
